language: node_js
jobs:
  include:
    - stage: npm release
      script: echo "Deploying to npm ..."
      deploy:
        provider: npm
        email: dev@inakiarroyo.com
        api_key: $NPM_API_KEY
        on:
          tags: true
          branch: master
